services/imagery/Dockerfile, services/imagery/README.md, services/imagery/src/backends/gphoto2-backend.js, services/imagery/src/service.js
This allows for multiple camera backends to exist if need be, and clears up naming confusion down the road.
There are not any unit tests configured for the imagery service, so to test it out I had to just comment out the body of `GPhoto2Backend._takePhoto` and `GPhoto2Backend._getCamera` and put a log in the middle to verify that the loop was running.
=> Rename the camera backend to a gphoto2 backend

services/mavproxy/Dockerfile
pymavlink version 2.2.11 does not build, and this mandates the version
to be <= 2.2.10.
=> Add constraint to pymavlink to fix mavproxy service builds

services/interop-proxy/test.sh, test/docker-compose.yml
This will prevent problems from happening in the future from when a
backwards-incompatible change is pushed to
`auvsisuas/interop-server:latest`.
Tagged deployments were added in auvsi-suas/interop#340.
After the end of October, the tag should be updated to `2018.10` and
interop-proxy should be modified (if needed) to work with it.
=> Freeze the interop server on the `2018.09` tag

services/forward-interop/.babelrc, services/pong/.babelrc, services/telemetry/.babelrc
It seems like there was a conflict with the built-in source mapping somewhere in Jest and the source-map-support babel plugin. It was working fine with the service source code, but not for the test cases. The `.babelrc`s are now configured to only use the source-map-support plugin when building the source code, and is not including when running tests, since Jest takes care of this.
=> Disable source-map-support for Jest to fix test error reporting

services/telemetry/src/plane.js, services/telemetry/test/service.test.js
Repeated requests to retrieve a mission will not make redundant entries in the queue - only one request will be made instead, and then the results of that request will be forwarded to all requesters. If a write request is placed on the queue, however, a write barrier is recognized, and therefore a new request to retrieve a mission will be placed on the queue.
=> Telemetry queue folding

services/interop-proxy/lib/interop_proxy/request.ex, services/interop-proxy/lib/interop_proxy/sanitize.ex, services/interop-proxy/test.sh, services/interop-proxy/test/interop_proxy/request_test.exs, services/interop-proxy/test/interop_proxy_test.exs, services/interop-proxy/test/interop_proxy_web/controllers/obstacles_controller_test.exs, test/docker-compose.yml
Moving obstacles were removed and thus references were removed from
interop-proxy. Note that they were not taken out of the protobuf, and so
would remain as a empty list. Also had to update the login request since
it uses JSON instead of a urlencoded body.
=> Update interop server to november release

services/interop-proxy/lib/interop_proxy/request.ex, services/interop-proxy/lib/interop_proxy_web/controllers/controller_helpers.ex
Right now everything becomes a 500, and so if invalid data is sent, it looks like interop proxy had an error and that the client was correct when they were not. This fixes that by simply giving the status code and the message on the interop server.
If an unexpected 2xx or 3xx code is returned, this will give a 500 as before with a message explaining it.
=> Return interop server status code on 4xx and 5xx

.travis.yml, ci/after-script.sh
Also updated to Xenial to allow for Python 3.7 in the future.
Needed to disable install commands because of Elixir.
=> Make the Travis config be more language-agnostic

services/common/nodejs/package.json
winston 3.2 was causing problems at the moment which do not need to be fixed yet. This fixes the build problems for now until the js services are compatible with winston >= 3.2.
=> Constrain winston to version 3.1

services/interop-proxy/Dockerfile, services/interop-proxy/test.sh, test/docker-compose.yml
Nothing eventful happened on the API side for users, so no changes to interop proxy were needed. Note that there was not a Janurary release of the interop server since the last commit on GitHub was on December 2nd.
=> Update interop server to December release

services/common/messages/imagery.proto
This lifts the proto path up to the `services/common` folder instead of `services/common/messages`. This is for making Python proto imports work more naturally, instead of requiring all Python generated code to go into the global import namespace because they were not being contained into a single module. (The protobuf people insist on not allowing relative imports for Python generated code which causes this problem.)
The package names are still the same to minimize disruption, though it seems to be more conventional to have the package name match the import path more closely. The existing implementations in services now don't use the regular protobuf compiler and don't seem to be phased by this change.
If y'all know of a better way to make Python generated protobuf modules happy let me …
=> Lift the proto path up a directory

services/common/messages/image_rec.proto, services/image-rec-master/Dockerfile.test, services/image-rec-master/README.md, services/image-rec-master/service/app.py, services/image-rec-master/service/tasks.py, services/image-rec-master/service/util.py, services/image-rec-master/test/test_app.py
The original intention was to have the other image services implement this functionality, but implementing in `image-rec-master` allows for this service to contain the entire Redis pipeline state. This reduces the code duplication needed for implementing functionality in other services, and takes care of the logic instead of needing to implement it when it's needed.
Adds the following endpoints:
- `GET /api/pipeline/images/:id` - this one just gets an image.
- `POST /api/pipeline/images/start-processing-next-auto` - retrieves the next image to run auto image rec on.
- `POST /api/pipeline/images/:id/finish-processing-auto` - ends the processing window for auto image rec.
- `POST /api/pipeline/images/process-next-manual` - returns and marks the next manual image as processed.
- `POST …
=> Add functionality for submitting targets and processing images

services/imagery/Dockerfile
Ground station has no limit - only the plane's imagery will (whose value is to be determined).
=> Set MAX_IMAGES to 0

services/imagery/Dockerfile, services/imagery/README.md, services/imagery/bin/start-service.js, services/imagery/src/backends/camera-base-backend.js, services/imagery/src/backends/gphoto2-backend.js, services/imagery/src/backends/z-cam-e1-backend.js, services/imagery/src/service.js, services/imagery/test/backends/z-cam-e1-backend.test.js, services/imagery/test/service.test.js
This enables the Z Cam E1 camera to be used in the imagery service by using the `CAMERA_HOST` and `CAMERA_PORT` environment variables.
In the process, a generic camera backend was created to share code between the the backend for `gphoto2`-supported cameras and the Z Cam E1 since the capture workflow is similar, and allows other camera backends to be added off of this.
I tested this using commands recorded from the Z Cam E1, but this should be tested with the actual camera before merging.
=> Add support for Z Cam E1

services/interop-proxy/test.sh, test/docker-compose.yml
The images on the `auvsisuas` Docker Hub organization are being deleted, and because of how fast the old one was removed given that the new one had been out a little more than a week, a mirror is needed to prevent build failures and other development problems.
In the future this also allows for mirroring images in the middle of a month, instead of waiting until the next.
=> Use a mirror of the interop server for testing

services/interop-proxy/Dockerfile, services/interop-proxy/Dockerfile.test, services/interop-proxy/mix.exs
Updates Elixir from 1.6 to 1.8 and updates Mix deps to new versions except for Poison since Phoenix wasn't compatible with 4.0 yet.
I was having some OpenSSL problems again, one of the dependencies being updated fixed the problem, but it's good to have them all updated anyways.
=> Update Elixir and Mix dependencies for interop-proxy

services/common/messages/interop.proto, services/interop-proxy/README.md, services/interop-proxy/lib/interop_proxy.ex, services/interop-proxy/lib/interop_proxy/application.ex, services/interop-proxy/lib/interop_proxy/message.ex, services/interop-proxy/lib/interop_proxy/request.ex, services/interop-proxy/lib/interop_proxy/sanitize.ex, services/interop-proxy/lib/interop_proxy/session.ex, services/interop-proxy/lib/interop_proxy_web/controllers/mission_controller.ex, services/interop-proxy/priv/flasked_env.exs, services/interop-proxy/test.sh, services/interop-proxy/test/interop_proxy/request_test.exs, services/interop-proxy/test/interop_proxy/session_test.exs, services/interop-proxy/test/interop_proxy_test.exs, services/interop-proxy/test/support/conn_case.ex, services/interop-proxy/test/test_helper.exs, test/docker-compose.yml
Updated Interop Proxy to work with the most recent Interop Server version. Note that because May is not complete yet, there could be changes after, as long as the Interop Proxy still works with the final May release of the Interop Server, the `uavaustin/interop-server:2019.05` tag will be updated.
The Interop Server saw changes to a several things:
- Requests are defined by a protobuf schema (still JSON though)
- In the process some fields were removed (like home position) or renamed.
- Enum fields need capital letters for the Python protobuf JSON parsing.
- Since default values can be left off in protobufs, the sanitize functions needed to account for default values just in case.
- Obstacles are now in the mission instead of their own endpoint.
- Mission ID is now required, for now this …
=> Update Interop Proxy for mid-May Interop Server release

services/imagery/src/image-store.js, services/imagery/test/image-store.test.js
Apparently, connection pools in SQLite are still too dumb to synchronize properly without triggering SQLITE_TIMEOUT, so I just decided to limit the connection pool to 1 to force mutual exclusion. However, I may have accidentally discovered a deadlock condition, given that the connection pool caused a timeout. I hope this is not the case.
Even with and without this fix, the tests for everything - not just the store - are failing once in a blue moon, which doesn't seem to be a good sign. What's worse is that the errors do not point to anything in particular - for instance, one error was about rolling back a transaction while a transaction was not underway. I checked the code path and there isn't a path where this could ever happen. Another error was a Z CAM E1 backend test saying that a …
=> Fix concurrency in imagery store

services/interop-proxy/Dockerfile, services/interop-proxy/config/config.exs, services/interop-proxy/lib/interop_proxy_web/router.ex
Phoenix was configured to only allow JSON to be specified, and this adds a custom MIME type to make sure we can specify protobuf as well without assuming it as the default value.
=> Allow accept header to be set to protobuf in Interop Proxy

.travis.yml, services/dashboard/Dockerfile, services/forward-interop/Dockerfile, services/forward-interop/Dockerfile.test, services/imagery/Dockerfile, services/imagery/Dockerfile.test, services/pong/Dockerfile, services/pong/Dockerfile.test, services/telemetry/Dockerfile, services/telemetry/Dockerfile.test
Imagery had to be held back to Node 10, as the gphoto2 bindings do not compile under Node 12:
../src/camera.cc: In static member function 'static void GPCamera::Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/camera.cc:43:38: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
43 |   constructor.Reset(tpl->GetFunction());
=> Upgrade from Node 8 to 12

services/interop-proxy/README.md, services/interop-proxy/lib/interop_proxy/session.ex, services/interop-proxy/priv/flasked_env.exs
Fix issue where interop-proxy overloads a common environment variable, `USERNAME`. Replaces the old `USERNAME` and `PASSWORD` environment variables with `INTEROP_USERNAME` and `INTEROP_PASSWORD`.
Also adds a more detailed error message when failing on login.
=> Fix interop-proxy authorization
